title: SWEN440
baseurl: ""
timezone: America/New_York

future: true
permalink: /:year/:month/:day/:title

group_name: "Group 2"
group_members:
  - Bill Dybas
  - Colton Venditto
  - Greg Rozmarynowycz
  - Steven Lavoie

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _scss
